routes/admin.php
<?php

//Admin routes
//mapped in Providers/RouteServiceProvider.php

Route::get('dashboard', 'HomeController@index')->name('inside.index');
Route::resource('admins', 'PanelUserController');
Route::resource('articles', 'ArticleController');
Route::resource('article-categories', 'ArticleCategoryController');
Route::resource('broken-links', 'BrokenLinkController')->only(['index', 'destroy']);
Route::resource('cities', 'CityController');
Route::resource('competitions', 'CompetitionController');
Route::resource('coaches', 'CoachController');
Route::get('coach-approvals', 'CoachPendingController')->name('coach-approvals.index');
Route::resource('coaches.media', 'CoachMediaController');
Route::resource('coaches.reviews', 'CoachReviewController');
Route::resource('countries', 'CountryController');
Route::resource('designers', 'DesignerController');
Route::resource('designer-coupons', 'DesignerCouponController');
Route::resource('designer-facts', 'DesignerFactController');
Route::resource('designer-meta-datum', 'DesignerMetaDataController');
Route::resource('designer-products', 'DesignerProductController');
Route::resource('designer-reviews', 'DesignerReviewController');
Route::resource('federations', 'FederationController');
Route::resource('galleries', 'GalleryController');
Route::resource('galleries.images', 'GalleryImageController');
Route::resource('sub-galleries', 'SubGalleryController');
Route::resource('products', 'ProductController');
Route::resource('product-categories', 'ProductCategoryController');
Route::resource('redirects', 'RedirectController');
Route::resource('services', 'ServiceController');
Route::resource('states', 'StateController');
Route::resource('shop-filters', 'FilterProductController');
Route::resource('tags', 'TagController');
Route::get('coach/images', 'CoachExtraController');//Coach image importer
Route::get('sync-competition-excel',
    'CompetitionExcelController')->name('sync-competition-excel');//Competitions excel sync
Route::get('import-excel', 'SheetHelperController');
Route::get('news/images', 'NewsExtraController@images');//News image importer
Route::get('product/images', 'ProductExtraController');//Product image importer
Route::get('news/api', 'NewsExtraController@api')->name('news.api');
Route::post('news/search', 'NewsExtraController@search')->name('news-search');
Route::post('news/save', 'NewsExtraController@save')->name('news-save');
Route::resource('news', 'NewsController');
Route::post('get-states-by-country', 'HelperController@states')->name('get-states');
Route::post('get-states-and-cities', 'HelperController@statesAndCities')->name('get-states-and-cities');
Route::post('get-states-and-cities-competition',
    'HelperController@statesAndCitiesForCompetition')->name('get-states-and-cities-competition');
Route::post('get-cities', 'HelperController@cities')->name('get-cities');
Route::post('coaches/{coach}/media/save-cropped', 'CoachMediaController@saveCropped');
Route::post('coaches/save-cropped', 'CoachController@saveCropped')->name('crop-and-save');
Route::post('galleries/save-order', 'GalleryController@saveOrder')->name('galleries.order');
Route::post('coaches-reviews/save-order', 'CoachReviewController@saveOrder')->name('coaches.reviews.order');
Route::post('coaches-media/save-order', 'CoachMediaController@saveOrder')->name('coaches.media.order');
//Approvals
Route::get('coaches-pending-review/detail/{pending}',
    'CoachPendingReviewController@detail')->name('coaches.pending-reviews.detail');
Route::post('coaches-pending-reviews/approve',
    'CoachPendingReviewController@approve')->name('coaches.pending-reviews.approve');
Route::delete('coaches-pending-reviews/reject',
    'CoachPendingReviewController@reject')->name('coaches.pending-reviews.reject');

Route::post('coaches-pending-media/approve',
    'CoachPendingMediaController@approve')->name('coaches.pending-media.approve');
Route::delete('coaches-pending-media/reject',
    'CoachPendingMediaController@reject')->name('coaches.pending-media.reject');


Route::get('coaches-pending-information/detail/{pending}',
    'CoachPendingInformationController@detail')->name('coaches.pending-information.detail');
Route::post('coaches-pending-information/approve',
    'CoachPendingInformationController@approve')->name('coaches.pending-information.approve');
Route::delete('coaches-pending-information/reject',
    'CoachPendingInformationController@reject')->name('coaches.pending-information.reject');

Route::get('/', 'HomeController@redirect');

routes/web.php
<?php

use Spatie\Honeypot\ProtectAgainstSpam;

// Authentication Routes...
Auth::routes();

//Admin routes in /routes/admin.php

Route::get('/apps/shopify', 'Apps\ShopifyController@index')->middleware(['auth.shop'])->name('home');

Route::get('admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('admin', 'Auth\LoginController@adminLogin');

Route::get('coach', 'Auth\LoginController@showCoachLoginForm');
Route::post('coach', 'Auth\LoginController@coachLogin');

//Route::get('bikini-designers', 'Designers\DesignerController@index');

#region Competitions

#region 301s

Route::get('past-competitions/{url}', 'Common\RedirectController@pastCompetitions');

//Bikini

Route::get('bikini-competitions-near-me', 'Common\RedirectController@bikiniCompetitionsNearMe');

Route::get('bikini-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword');

//End bikini

//Figure

Route::get('figure-and-physique-competitions-near-me', 'Common\RedirectController@figurePhysiqueCompetitionsNearMe');

Route::get('figure-and-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword');

Route::get('figure-physique-competitions-near-me', 'Common\RedirectController@figurePhysiqueCompetitionsNearMe');

Route::get('figure-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword');

Route::get('competitions/figure-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword')
    ->where('keyword', '^((?!near-me).)*$');

//End figure

//Bodybuilding

Route::get('bodybuilding-competitions-near-me', 'Common\RedirectController@bodybuildingCompetitionsNearMe');

Route::get('bodybuilding-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword');

Route::get('competitions/bodybuilding-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword')
    ->where('keyword', '^((?!near-me).)*$');

//End bodybuilding

Route::get('news/chinese-female-bodybuilder-speaks-on-viral-fame-after-naked-pics-cause-internet-stir','Common\RedirectController@specialOne');

//Online coaches
Route::get('online-bikini-competition-coaches','Common\RedirectController@onlineBikiniCompetitionCoaches');
Route::get('online-figure-competition-coaches','Common\RedirectController@onlineFigureCompetitionCoaches');
Route::get('online-bodybuilding-coaches','Common\RedirectController@onlineBodybuildingCoaches');

#endregion

#region Competitions
Route::namespace('Competitions')
    ->where(['keyword' => '[A-Za-z-]+'])
    ->prefix('competitions')
    ->group(static function () {
        Route::get('bikini-competitions-near-me', 'SearchNearMeController')
            ->name('bikini-competitions-near-me');

        Route::get('figure-physique-competitions-near-me', 'SearchNearMeController');

        Route::get('bodybuilding-competitions-near-me', 'SearchNearMeController');

        Route::get('bikini-competitions-{keyword}', 'SearchByUrlController');

        //Route::get('figure-physique-competitions-{keyword}', 'SearchByUrlController');

        //Route::get('bodybuilding-competitions-{keyword}', 'SearchByUrlController');

        Route::post('get-competitions-by-keyword', 'SearchByKeywordController')
            ->name('get-competitions-by-keyword');

        Route::get('{slug}',
            'CompetitionDetailController')->name('competition-detail')->where(['slug' => '^[a-z0-9-]+$']);

    });

#endregion

#region Coaches
Route::namespace('Coaches')
    ->where(['keyword' => '[A-Za-z-]+'])
    ->prefix('coaches')
    ->group(static function () {
        //Near Me
        Route::get('bikini-competition-coaches-near-me', 'CoachNearMeController')
            ->name('bikini-competition-coaches-near-me');

        Route::get('figure-physique-competition-coaches-near-me', 'CoachNearMeController')
            ->name('figure-physique-competition-coaches-near-me');

        Route::get('bodybuilding-coaches-near-me', 'CoachNearMeController')
            ->name('bodybuilding-coaches-near-me');
        //
        //Online
        Route::get('online-bikini-competition-coaches', 'CoachOnlineController');

        Route::get('online-figure-competition-coaches', 'CoachOnlineController');

        Route::get('online-bodybuilding-coaches', 'CoachOnlineController');
        //
        //By Keyword
        Route::get('bikini-competition-coaches-{keyword}', 'CoachByUrlController');

        Route::get('figure-physique-competition-coaches-{keyword}', 'CoachByUrlController');

        Route::get('bodybuilding-coaches-{keyword}', 'CoachByUrlController');

        Route::get('{slug}', 'CoachShowController')
            ->name('coach-profile');
        //
        //Ajax call
        Route::post('get-coaches-by-keyword', 'CoachByKeywordController')
            ->name('get-coaches-by-keyword');

    });
#endregion

#region Bikini Makers
Route::namespace('BikiniMakers')
    ->where(['designer_slug' => '[A-Za-z-]+'])
    ->prefix('bikini-makers')
    ->name('designer.')
    ->group(static function () {
        Route::get('competition-bikinis-by-amber-competition-bikinis',
            'ProductController@bikini')->defaults('designer_slug', 'amber-competition-bikinis');
        Route::get('amber-competition-bikinis', 'MakerController@show')->defaults('designer_slug',
            'amber-competition-bikinis');
        Route::get('{designer_slug}-facts', 'FactController@index')->name('facts');
        Route::get('{designer_slug}-reviews', 'ReviewController@index')->name('reviews');
        Route::get('{designer_slug}-promo-codes', 'PromoCodeController@index')->name('promo-codes');
        Route::get('{designer_slug}-competition-bikinis', 'ProductController@bikini')->name('products-bikini');
        Route::get('{designer_slug}-figure-suits', 'ProductController@figure')->name('products-figure-suit');
        Route::get('{designer_slug}', 'MakerController@show')->name('home');
        Route::get('/', 'ListController@index')->name('list');
    });
#endregion

#region Products
Route::namespace('Products')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('store')
    ->group(static function () {
        Route::get('/', 'ListProductsController')->name('store');
        Route::get('/products/{slug}', 'ShowProductController')->name('store-product-detail');
        Route::get('/{slug}', 'FilterProductController');
    });
#endregion

#region News
Route::namespace('News')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('news')
    ->group(static function () {
        Route::get('/', 'ListNewsController')->name('news');
        Route::get('search', 'SearchNewsController')->name('news-search');
        Route::post('more', 'MoreNewsController')->name('news-more');
        Route::get('{slug}', 'ShowNewsController')->name('news-detail');

    });
#endregion

#region Articles
Route::namespace('Articles')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('comp-prep')
    ->group(static function () {
        Route::get('/', 'ListArticleController')->name('comp-prep');
        Route::get('search', 'SearchArticleController')->name('comp-prep-search');
        Route::post('more', 'MoreArticleController')->name('comp-prep-more');
        Route::get('{slug}', 'ShowArticleController')->name('comp-prep-detail');

    });
#endregion

#region Gallery
//Route::namespace('Common')
//    ->where(['gallery_slug' => '^[a-z0-9-]+$'])
//    ->prefix('gallery')
//    ->group(static function () {
//        Route::get('search', 'GalleryController@search')->name('show-search');
//        Route::get('{gallery_slug}/{shortcode}', 'GalleryController@detail')->name('show-image');
//        Route::get('{gallery_slug}', 'GalleryController@show')->name('show-gallery');
//        Route::get('/', 'GalleryController@index')->name('gallery');
//    });
#endregion

Route::namespace('WooCommerce')
    ->prefix('woocommerce')
    //->middleware(['web', 'auth:designer', 'noCache', 'revalidate'])//todo: comment out
    ->group(static function () {
        Route::get('create', 'CreateAuthUrl')->name('gen-url');
        Route::post('callback', 'HandleDataAfterCallback');
        Route::get('products', 'GetProducts');
        Route::get('coupons', 'GetCoupons');
    });

#region Other
Route::get('/vbulletin', 'Common\VBulletinController@index')->name('vbulletin');
Route::get('/contact-us', 'Common\ContactFormController@index')->name('contact-us');
Route::post('/send-message-to-coach', 'Common\SendMessageToCoachController@save')->name('send-message-to-coach');
Route::post('/save-contact-us', 'Common\ContactFormController@save')
    ->middleware(ProtectAgainstSpam::class)
    ->name('save-contact-us');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')
    ->middleware('basicAuth');
Route::get('/', 'Common\HomeController')->name('index');
#endregion

app/Http/Controllers/BikiniMakers/ReviewController.php
<?php

namespace App\Http\Controllers\BikiniMakers;

use App\Models\Designer;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ReviewController extends Controller
{
    public function index($designer_slug = null)
    {
        try {

            $designer = app(Designer::class)->whereSlug($designer_slug)->firstOrFail();

        } catch (ModelNotFoundException $exception) {

            return redirect()->back();

        }

        $reviews        = $designer->reviews()->get();
        $meta           = $designer->meta_data('reviews')->get();
        $sell_channels  = explode('|', $designer->sell_channels);
        $also_available = explode('|', $designer->also_available);
        $title          = $meta->where('section', 'title')->first()->content;

        \SEOMeta::setTitle($meta->where('section', 'meta_title')->first()->content);
        \SEOMeta::setDescription($meta->where('section', 'meta_description')->first()->content);

        \OpenGraph::setTitle($meta->where('section', 'meta_title')->first()->content);
        \OpenGraph::setDescription($meta->where('section', 'meta_description')->first()->content);

        return view('site.designer.reviews',
            compact('designer', 'reviews', 'meta', 'sell_channels', 'also_available', 'title'));

    }
}

app/Http/Controllers/Coaches/CoachByKeywordController.php
<?php

namespace App\Http\Controllers\Coaches;

use App\Http\Resources\CoachResource;
use Cache;
use Illuminate\Http\Request;

class CoachByKeywordController extends CoachController
{

    public function __invoke(Request $request)
    {
        if (!$request->latitude || !$request->longitude) {
            return '';
        }

        session([
            'latitude'   => $request->latitude,
            'longitude'  => $request->longitude,
            'place_name' => $request->place_name,
        ]);

        if ($request->online) {
            $coaches = Cache::tags('coaches-online')->remember("coaches+online+$request->type+$request->latitude+$request->longitude",
                env('ONE_DAY_TTL'),
                function () use ($request) {
                    return $this->getCoachesOnline($request, $request->type);
                });
        } else {
            $coaches = Cache::tags('coaches-online')->remember("coaches+$request->type+$request->latitude+$request->longitude",
                env('ONE_DAY_TTL'),
                function () use ($request) {
                    return $this->getCoaches($request, 'search_service_options', $request->type);
                });
        }

        return CoachResource::collection($coaches);
    }

}

app/Http/Controllers/Coaches/CoachShowController.php
<?php

namespace App\Http\Controllers\Coaches;

use App\Models\Coach;
use Cache;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use OpenGraph;
use SEOMeta;

class CoachShowController extends CoachController
{

    public function __invoke($slug)
    {
        try {

            $coach = Cache::tags('coach-detail')->remember(
                'coach-detail-' . request()->segment(2),
                env('ONE_DAY_TTL'),
                static function () use ($slug) {
                    return app(Coach::class)
                        ->with(
                            'service_options:coach_id,name',
                            'division_options:coach_id,name',
                            'federation_options:coach_id,value',
                            'reviews:coach_id,content,reviewer_info',
                            'media_contents:coach_id,path,thumb_path',
                            'meta_data:coach_id,content'
                        )
                        ->where('slug', $slug)
                        ->firstOrFail();
                }
            );

            SEOMeta::setTitle($coach->meta_data->first()->content ?? '');
            SEOMeta::setDescription($coach->meta_data->last()->content ?? '');

            OpenGraph::setTitle($coach->meta_data->first()->content ?? '');
            OpenGraph::addImage($coach->profile_picture);
            OpenGraph::setDescription($coach->meta_data->last()->content ?? '');

            $back = session('back_url');

            return view('site.coach.profile', compact('coach', 'back'));
        } catch (ModelNotFoundException $exception) {

            return redirect()->route('bikini-competition-coaches-near-me');
        }
    }
}

resources/views/admin/coach/review/add.blade.php
@extends('layouts.layout-2')

@section('styles')
    <link href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
@endsection

@section('scripts')
    <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>

    <script>
        $(function () {

            $('#content').summernote({
                height: 250
            });
        });
    </script>
@endsection

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            Add Review for <strong>{{$coach->name}}</strong>
        </h6>
        <div class="card-body">
            <form autocomplete='off' method="post" action="{{route('back-office.coaches.reviews.store',['coach' => $coach->id])}}">
                @csrf
                <div class="form-group">
                    <label class="form-label">{{__('Reviewer Name')}}</label>
                    <input id="name" type="text" name="reviewer_info" value="{{ old('reviewer_info') }}"
                           class="form-control @error('reviewer_info') is-invalid @enderror">
                    @error('reviewer_info')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Content')}}</label>
                    <textarea id="content" class="form-control @error('content') is-invalid @enderror"
                              name="content">{{old('content')}}</textarea>
                    @error('content')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/coach/review/edit.blade.php
@extends('layouts.layout-2')

@section('styles')
    <link href="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.css" rel="stylesheet">
@endsection

@section('scripts')
    <script src="//cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote-lite.js"></script>

    <script>
        $(function () {

            $('#content').summernote({
                height: 250
            });
        });
    </script>
@endsection

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            Update Review for <strong>{{$data->coach->name}}</strong>
        </h6>
        <div class="card-body">
            <form autocomplete='off' method="post" action="{{route('back-office.coaches.reviews.update',['coach' => $data->coach->id, 'review' => $data->id])}}">
                @csrf
                @method('PUT')
                <div class="form-group">
                    <label class="form-label">{{__('Reviewer Name')}}</label>
                    <input id="name" type="text" name="reviewer_info" value="{{ old('reviewer_info', $data->reviewer_info) }}"
                           class="form-control @error('reviewer_info') is-invalid @enderror">
                    @error('reviewer_info')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Content')}}</label>
                    <textarea id="content" class="form-control @error('content') is-invalid @enderror"
                              name="content">{{old('content', $data->content)}}</textarea>
                    @error('content')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/coach/review/list.blade.php
@extends('layouts.layout-2')

@section('scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Sortable/1.10.1/Sortable.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery-sortablejs@latest/jquery-sortable.js"></script>

    @include('admin.partial.swal',['word'=>'review'])

    <script>
        $(function () {

            const toast = Swal.mixin({
                toast: true,
                position: 'top',
                showConfirmButton: false,
                timer: 3000
            });

            $('tbody').sortable({
                animation: 150,
                ghostClass: 'blue-background-class',
                invertSwap: true,
                dataIdAttr: 'data-id',
                onSort: function (evt) {
                    $.post("{{route('back-office.coaches.reviews.order')}}", {data: this.toArray()}, function (res) {
                        if (res.success) {
                            toast.fire({
                                type: 'success',
                                title: 'Saved!'
                            })
                        } else {
                            console.log(res);
                        }
                    }, 'json');
                },
            })
        });
    </script>
@endsection

@section('styles')
    <style>
        .table tr {
            cursor: move;
        }
    </style>
@endsection

@section('content')
    <div class="card">

        <h6 class="card-header with-elements">
            <div class="card-header-title">Reviews of <strong>{{$coach->name}}</strong></div>
            <div class="card-header-elements ml-auto">
                <a href="{{route('back-office.coaches.reviews.create', ['coach' => $coach->id])}}"
                   class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> Add New</a>
            </div>
        </h6>

        @if($coach->reviews->count() > 0)
            <div class="alert alert-info alert-dismissible fade show my-3 mx-3">
                Drag & drop the line to change review order
            </div>
            <table class="table card-table table-hover table-striped">
                <thead class="thead-light">
                <tr>
                    <th>Reviewer</th>
                    <th>Review</th>
                    <th style="text-align: right">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($coach->reviews as $row)
                    <tr data-id="{{$row->id}}">
                        <td class="align-middle">{{$row->reviewer_info}}</td>
                        <td class="align-middle">{!! $row->content !!}</td>
                        <td style="text-align: right">
                            <a href="{{route('back-office.coaches.reviews.edit',['coach'=>$coach->id, 'review'=>$row->id])}}"
                               class="btn btn-sm icon-btn btn-outline-info">
                                <span class="fa fa-pencil-alt"></span>
                            </a>
                            <a href="#" data-url="/back-office/coaches/{{$coach->id}}/reviews/{{$row->id}}"
                               data-id="{{$row->id}}"
                               class="btn btn-sm icon-btn btn-outline-danger delete">
                                <span class="fa fa-trash"></span>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        @else
            <div class="alert alert-warning alert-dismissible fade show my-3 mx-3">
                There is not any reviews for <strong>{{$coach->name}}</strong>...
            </div>
        @endif
    </div>
@endsection