routes/admin.php
<?php

//Admin routes
//mapped in Providers/RouteServiceProvider.php

Route::get('dashboard', 'HomeController@index')->name('inside.index');
Route::resource('admins', 'PanelUserController');
Route::resource('articles', 'ArticleController');
Route::resource('article-categories', 'ArticleCategoryController');
Route::resource('broken-links', 'BrokenLinkController')->only(['index', 'destroy']);
Route::resource('cities', 'CityController');
Route::resource('competitions', 'CompetitionController');
Route::resource('coaches', 'CoachController');
Route::get('coach-approvals', 'CoachPendingController')->name('coach-approvals.index');
Route::resource('coaches.media', 'CoachMediaController');
Route::resource('coaches.reviews', 'CoachReviewController');
Route::resource('countries', 'CountryController');
Route::resource('designers', 'DesignerController');
Route::resource('designer-coupons', 'DesignerCouponController');
Route::resource('designer-facts', 'DesignerFactController');
Route::resource('designer-meta-datum', 'DesignerMetaDataController');
Route::resource('designer-products', 'DesignerProductController');
Route::resource('designer-reviews', 'DesignerReviewController');
Route::resource('federations', 'FederationController');
Route::resource('galleries', 'GalleryController');
Route::resource('galleries.images', 'GalleryImageController');
Route::resource('sub-galleries', 'SubGalleryController');
Route::resource('products', 'ProductController');
Route::resource('product-categories', 'ProductCategoryController');
Route::resource('redirects', 'RedirectController');
Route::resource('services', 'ServiceController');
Route::resource('states', 'StateController');
Route::resource('shop-filters', 'FilterProductController');
Route::resource('tags', 'TagController');
Route::get('coach/images', 'CoachExtraController');//Coach image importer
Route::get('sync-competition-excel',
    'CompetitionExcelController')->name('sync-competition-excel');//Competitions excel sync
Route::get('import-excel', 'SheetHelperController');
Route::get('news/images', 'NewsExtraController@images');//News image importer
Route::get('product/images', 'ProductExtraController');//Product image importer
Route::get('news/api', 'NewsExtraController@api')->name('news.api');
Route::post('news/search', 'NewsExtraController@search')->name('news-search');
Route::post('news/save', 'NewsExtraController@save')->name('news-save');
Route::resource('news', 'NewsController');
Route::post('get-states-by-country', 'HelperController@states')->name('get-states');
Route::post('get-states-and-cities', 'HelperController@statesAndCities')->name('get-states-and-cities');
Route::post('get-states-and-cities-competition',
    'HelperController@statesAndCitiesForCompetition')->name('get-states-and-cities-competition');
Route::post('get-cities', 'HelperController@cities')->name('get-cities');
Route::post('coaches/{coach}/media/save-cropped', 'CoachMediaController@saveCropped');
Route::post('coaches/save-cropped', 'CoachController@saveCropped')->name('crop-and-save');
Route::post('galleries/save-order', 'GalleryController@saveOrder')->name('galleries.order');
Route::post('coaches-reviews/save-order', 'CoachReviewController@saveOrder')->name('coaches.reviews.order');
Route::post('coaches-media/save-order', 'CoachMediaController@saveOrder')->name('coaches.media.order');
//Approvals
Route::get('coaches-pending-review/detail/{pending}',
    'CoachPendingReviewController@detail')->name('coaches.pending-reviews.detail');
Route::post('coaches-pending-reviews/approve',
    'CoachPendingReviewController@approve')->name('coaches.pending-reviews.approve');
Route::delete('coaches-pending-reviews/reject',
    'CoachPendingReviewController@reject')->name('coaches.pending-reviews.reject');

Route::post('coaches-pending-media/approve',
    'CoachPendingMediaController@approve')->name('coaches.pending-media.approve');
Route::delete('coaches-pending-media/reject',
    'CoachPendingMediaController@reject')->name('coaches.pending-media.reject');


Route::get('coaches-pending-information/detail/{pending}',
    'CoachPendingInformationController@detail')->name('coaches.pending-information.detail');
Route::post('coaches-pending-information/approve',
    'CoachPendingInformationController@approve')->name('coaches.pending-information.approve');
Route::delete('coaches-pending-information/reject',
    'CoachPendingInformationController@reject')->name('coaches.pending-information.reject');

Route::get('/', 'HomeController@redirect');

routes/web.php
<?php

use Spatie\Honeypot\ProtectAgainstSpam;

// Authentication Routes...
Auth::routes();

//Admin routes in /routes/admin.php

Route::get('/apps/shopify', 'Apps\ShopifyController@index')->middleware(['auth.shop'])->name('home');

Route::get('admin', 'Auth\LoginController@showAdminLoginForm');
Route::post('admin', 'Auth\LoginController@adminLogin');

Route::get('coach', 'Auth\LoginController@showCoachLoginForm');
Route::post('coach', 'Auth\LoginController@coachLogin');

//Route::get('bikini-designers', 'Designers\DesignerController@index');

#region Competitions

#region 301s

Route::get('past-competitions/{url}', 'Common\RedirectController@pastCompetitions');

//Bikini

Route::get('bikini-competitions-near-me', 'Common\RedirectController@bikiniCompetitionsNearMe');

Route::get('bikini-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword');

//End bikini

//Figure

Route::get('figure-and-physique-competitions-near-me', 'Common\RedirectController@figurePhysiqueCompetitionsNearMe');

Route::get('figure-and-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword');

Route::get('figure-physique-competitions-near-me', 'Common\RedirectController@figurePhysiqueCompetitionsNearMe');

Route::get('figure-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword');

Route::get('competitions/figure-physique-competitions-{keyword}', 'Common\RedirectController@figureAndPhysiqueCompetitionsKeyword')
    ->where('keyword', '^((?!near-me).)*$');

//End figure

//Bodybuilding

Route::get('bodybuilding-competitions-near-me', 'Common\RedirectController@bodybuildingCompetitionsNearMe');

Route::get('bodybuilding-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword');

Route::get('competitions/bodybuilding-competitions-{keyword}', 'Common\RedirectController@bikiniCompetitionsKeyword')
    ->where('keyword', '^((?!near-me).)*$');

//End bodybuilding

Route::get('news/chinese-female-bodybuilder-speaks-on-viral-fame-after-naked-pics-cause-internet-stir','Common\RedirectController@specialOne');

//Online coaches
Route::get('online-bikini-competition-coaches','Common\RedirectController@onlineBikiniCompetitionCoaches');
Route::get('online-figure-competition-coaches','Common\RedirectController@onlineFigureCompetitionCoaches');
Route::get('online-bodybuilding-coaches','Common\RedirectController@onlineBodybuildingCoaches');

#endregion

#region Competitions
Route::namespace('Competitions')
    ->where(['keyword' => '[A-Za-z-]+'])
    ->prefix('competitions')
    ->group(static function () {
        Route::get('bikini-competitions-near-me', 'SearchNearMeController')
            ->name('bikini-competitions-near-me');

        Route::get('figure-physique-competitions-near-me', 'SearchNearMeController');

        Route::get('bodybuilding-competitions-near-me', 'SearchNearMeController');

        Route::get('bikini-competitions-{keyword}', 'SearchByUrlController');

        //Route::get('figure-physique-competitions-{keyword}', 'SearchByUrlController');

        //Route::get('bodybuilding-competitions-{keyword}', 'SearchByUrlController');

        Route::post('get-competitions-by-keyword', 'SearchByKeywordController')
            ->name('get-competitions-by-keyword');

        Route::get('{slug}',
            'CompetitionDetailController')->name('competition-detail')->where(['slug' => '^[a-z0-9-]+$']);

    });

#endregion

#region Coaches
Route::namespace('Coaches')
    ->where(['keyword' => '[A-Za-z-]+'])
    ->prefix('coaches')
    ->group(static function () {
        //Near Me
        Route::get('bikini-competition-coaches-near-me', 'CoachNearMeController')
            ->name('bikini-competition-coaches-near-me');

        Route::get('figure-physique-competition-coaches-near-me', 'CoachNearMeController')
            ->name('figure-physique-competition-coaches-near-me');

        Route::get('bodybuilding-coaches-near-me', 'CoachNearMeController')
            ->name('bodybuilding-coaches-near-me');
        //
        //Online
        Route::get('online-bikini-competition-coaches', 'CoachOnlineController');

        Route::get('online-figure-competition-coaches', 'CoachOnlineController');

        Route::get('online-bodybuilding-coaches', 'CoachOnlineController');
        //
        //By Keyword
        Route::get('bikini-competition-coaches-{keyword}', 'CoachByUrlController');

        Route::get('figure-physique-competition-coaches-{keyword}', 'CoachByUrlController');

        Route::get('bodybuilding-coaches-{keyword}', 'CoachByUrlController');

        Route::get('{slug}', 'CoachShowController')
            ->name('coach-profile');
        //
        //Ajax call
        Route::post('get-coaches-by-keyword', 'CoachByKeywordController')
            ->name('get-coaches-by-keyword');

    });
#endregion

#region Bikini Makers
Route::namespace('BikiniMakers')
    ->where(['designer_slug' => '[A-Za-z-]+'])
    ->prefix('bikini-makers')
    ->name('designer.')
    ->group(static function () {
        Route::get('competition-bikinis-by-amber-competition-bikinis',
            'ProductController@bikini')->defaults('designer_slug', 'amber-competition-bikinis');
        Route::get('amber-competition-bikinis', 'MakerController@show')->defaults('designer_slug',
            'amber-competition-bikinis');
        Route::get('{designer_slug}-facts', 'FactController@index')->name('facts');
        Route::get('{designer_slug}-reviews', 'ReviewController@index')->name('reviews');
        Route::get('{designer_slug}-promo-codes', 'PromoCodeController@index')->name('promo-codes');
        Route::get('{designer_slug}-competition-bikinis', 'ProductController@bikini')->name('products-bikini');
        Route::get('{designer_slug}-figure-suits', 'ProductController@figure')->name('products-figure-suit');
        Route::get('{designer_slug}', 'MakerController@show')->name('home');
        Route::get('/', 'ListController@index')->name('list');
    });
#endregion

#region Products
Route::namespace('Products')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('store')
    ->group(static function () {
        Route::get('/', 'ListProductsController')->name('store');
        Route::get('/products/{slug}', 'ShowProductController')->name('store-product-detail');
        Route::get('/{slug}', 'FilterProductController');
    });
#endregion

#region News
Route::namespace('News')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('news')
    ->group(static function () {
        Route::get('/', 'ListNewsController')->name('news');
        Route::get('search', 'SearchNewsController')->name('news-search');
        Route::post('more', 'MoreNewsController')->name('news-more');
        Route::get('{slug}', 'ShowNewsController')->name('news-detail');

    });
#endregion

#region Articles
Route::namespace('Articles')
    ->where(['slug' => '^[a-z0-9-]+$'])
    ->prefix('comp-prep')
    ->group(static function () {
        Route::get('/', 'ListArticleController')->name('comp-prep');
        Route::get('search', 'SearchArticleController')->name('comp-prep-search');
        Route::post('more', 'MoreArticleController')->name('comp-prep-more');
        Route::get('{slug}', 'ShowArticleController')->name('comp-prep-detail');

    });
#endregion

#region Gallery
//Route::namespace('Common')
//    ->where(['gallery_slug' => '^[a-z0-9-]+$'])
//    ->prefix('gallery')
//    ->group(static function () {
//        Route::get('search', 'GalleryController@search')->name('show-search');
//        Route::get('{gallery_slug}/{shortcode}', 'GalleryController@detail')->name('show-image');
//        Route::get('{gallery_slug}', 'GalleryController@show')->name('show-gallery');
//        Route::get('/', 'GalleryController@index')->name('gallery');
//    });
#endregion

Route::namespace('WooCommerce')
    ->prefix('woocommerce')
    //->middleware(['web', 'auth:designer', 'noCache', 'revalidate'])//todo: comment out
    ->group(static function () {
        Route::get('create', 'CreateAuthUrl')->name('gen-url');
        Route::post('callback', 'HandleDataAfterCallback');
        Route::get('products', 'GetProducts');
        Route::get('coupons', 'GetCoupons');
    });

#region Other
Route::get('/vbulletin', 'Common\VBulletinController@index')->name('vbulletin');
Route::get('/contact-us', 'Common\ContactFormController@index')->name('contact-us');
Route::post('/send-message-to-coach', 'Common\SendMessageToCoachController@save')->name('send-message-to-coach');
Route::post('/save-contact-us', 'Common\ContactFormController@save')
    ->middleware(ProtectAgainstSpam::class)
    ->name('save-contact-us');
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')
    ->middleware('basicAuth');
Route::get('/', 'Common\HomeController')->name('index');
#endregion

app/Http/Controllers/Admin/StateController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\StateRequest;
use App\Models\Country;
use App\Models\State;
use App\Repositories\Repository as Repo;
use Illuminate\Contracts\View\Factory;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Http\RedirectResponse;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use Illuminate\View\View;
use Log;

class StateController extends Controller
{

    protected $country;
    protected $state;

    public function __construct(Country $country, State $state)
    {
        // Set the models
        $this->country = new Repo($country);
        $this->state   = new Repo($state);
    }

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $keyword = '';

        if (\request('keyword')) {

            $keyword = \request('keyword');

            $data = $this->state
                ->with('country')
                ->orderBy('country_id')
                ->where('name', 'LIKE', '%'.$keyword.'%')
                ->paginate();

            $data->appends(['keyword' => $keyword]);

        } else {

            $data = $this->state->with('country')->orderBy('country_id')->paginate();

        }

        return view('admin.states.list', compact('data', 'keyword'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|Response|View
     */
    public function create()
    {
        $countries = $this->country->orderBy('name')->get();

        return view('admin.states.add', compact('countries'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  StateRequest  $request
     * @return RedirectResponse
     */
    public function store(StateRequest $request)
    {
        $this->state->create($request->all());

        return redirect()->route('back-office.states.index')->with('success', 'State has been created.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Factory|RedirectResponse|Response|View
     */
    public function edit($id)
    {
        try {

            $data = $this->state->find($id);

        } catch (ModelNotFoundException $e) {

            Log::error('State not found : User = '.auth()->user()->user_name.' , Message : '.$e->getMessage());

            return redirect()->route('back-office.states.index');

        }

        $countries = $this->country->orderBy('name')->get();

        return view('admin.states.edit', compact('data', 'countries'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  StateRequest  $request
     * @param  int  $id
     * @return RedirectResponse|Response
     */
    public function update(StateRequest $request, $id)
    {
        try {
            $data = $this->state->find($id);

            $data->update($request->all());

        } catch (ModelNotFoundException $exception) {
            return redirect()->route('back-office.states.index');
        }

        return redirect()->route('back-office.states.index')->with('success', 'State has been updated.');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        try {

            app(State::class)->findOrFail($id)->delete();

            session()->flash('success', 'State has been deleted.');

        } catch (ModelNotFoundException $e) {

            Log::error('State not found : User = '.auth()->user()->user_name.' , Message : '.$e->getMessage());

            //AppServiceProvider macro
            return response()->fail();
        }

        //AppServiceProvider macro
        return response()->success();
    }
}

resources/views/admin/states/add.blade.php
@extends('layouts.layout-2')

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            State
        </h6>
        <div class="card-body">
            <form autocomplete='off' method="post" action="{{route('back-office.states.store')}}">
                @csrf
                <div class="form-group">
                    <label class="form-label">{{__('Country')}}</label>
                    <select name="country_id" class="col-3 form-control selectpicker @error('country_id') is-invalid @enderror"
                            data-style="btn-default">
                            @foreach($countries as $country)
                                <option value="{{$country->id}}" @if(old('country_id') === $country->id) selected @endif>{{$country->name}}</option>
                            @endforeach
                    </select>

                    @error('country_id')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Name')}}</label>
                    <input type="text" name="name" value="{{ old('name') }}"
                           class="form-control @error('name') is-invalid @enderror">
                    @error('name')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Abbreviation (ISO)')}}</label>
                    <input type="text" name="iso" value="{{ old('iso') }}"
                           class="form-control @error('iso') is-invalid @enderror">
                    @error('iso')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/states/edit.blade.php
\@extends('layouts.layout-2')

@section('content')
    <div class="card mb-4">
        <h6 class="card-header">
            State
        </h6>
        <div class="card-body">
            <form autocomplete='off' method="post" action="{{route('back-office.states.update',['state'=>$data->id])}}">
                @csrf
                @method('PATCH')
                <div class="form-group">
                    <label class="form-label">{{__('Country')}}</label>
                    <select name="country_id"
                            class="col-3 form-control selectpicker @error('country_id') is-invalid @enderror"
                            data-style="btn-default">
                        @foreach($countries as $country)
                            <option value="{{$country->id}}"
                                    @if(old('country_id', $data->country_id) === $country->id) selected @endif>
                                {{$country->name}}
                            </option>
                        @endforeach
                    </select>

                    @error('country_id')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Name')}}</label>
                    <input type="text" name="name" value="{{ old('name', $data->name) }}"
                           class="form-control @error('name') is-invalid @enderror">
                    @error('name')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>

                <div class="form-group">
                    <label class="form-label">{{__('Abbreviation (ISO)')}}</label>
                    <input type="text" name="iso" value="{{ old('iso', $data->iso) }}"
                           class="form-control @error('iso') is-invalid @enderror">
                    @error('iso')
                    <small class="invalid-feedback">
                        <strong>{{ $message }}</strong>
                    </small>
                    @enderror
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/states/list.blade.php
@extends('layouts.layout-2')

@section('scripts')
    @include('admin.partial.swal',['word'=>'state'])
@endsection

@section('content')
    <div class="card">
        <div class="card-header">States</div>

        <div class="mt-3 ml-2 mb-0">
            <form class="form-inline mb-3">
                <input type="text" name="keyword" required class="form-control mr-sm-2 mb-sm-0 w-75"
                       placeholder="By State Name" value="{{$keyword}}">
                <button type="submit" class="btn btn-primary">Search</button>
                <a href="{{route('back-office.states.index')}}" class="btn btn-default ml-2">Reset</a>
            </form>
        </div>

        @if($data->count() > 0)
            <table class="table card-table table-hover">
                <thead class="thead-light">
                <tr>
                    <th>Country</th>
                    <th>Name</th>
                    <th>Abbr</th>
                    <th style="text-align: right">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($data as $row)
                    <tr>
                        <td class="align-middle">{{$row->country->name}}</td>
                        <td class="align-middle">{{$row->name}}</td>
                        <td class="align-middle">{{$row->iso ?? ''}}</td>
                        <td style="text-align: right">
                            <a href="{{route('back-office.states.edit',['state'=>$row->id])}}"
                               class="btn btn-sm icon-btn btn-outline-info">
                                <span class="fa fa-pencil-alt"></span>
                            </a>
                            <a href="#" data-url="/back-office/states/{{$row->id}}" data-id="{{$row->id}}"
                               class="btn btn-sm icon-btn btn-outline-danger delete">
                                <span class="fa fa-trash"></span>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="card-footer">
                {{ $data->links() }}
            </div>
        @else
            <div class="alert alert-warning alert-dismissible fade show my-3 mx-3">
                There is not any states for <strong>{{$keyword}}</strong>...
            </div>
        @endif
    </div>
@endsection